### ISSUE TITLE
Error when importing module after encrypting...

### ISSUE THREAD

**Issue by leomatias** [the-xentropy/xencrypt#1]
﻿function : The term '﻿function' is not recognized as the name of a cmdlet, function, script file, or operable

**Comment by the-xentropy** [comment]
I got this issue when trying to run a newer Mimikatz on an older version of Windows, but then I also got that error just running the script normally. Can you provide me with more information about what you're trying to do?

**Comment by the-xentropy** [comment]
I'm closing this for now because it's an error I recognize as being related to something else. If you comment with more info that I could use to potentially fix the issue if I'm wrong then I'll re-open the issue and fix it.
